import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { classNames } from "@/utils/classnames";
import Sidebar from "./Sidebar";
import Header from "./Header";
import { SidebarProvider } from "providers/SidebarProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className={classNames(inter.className, "h-full")}>
        <SidebarProvider>
          <div>
            <Sidebar />
            <div className="lg:pl-72">
              <Header />

              <main className="py-10">
                <div className="px-4 sm:px-6 lg:px-8">{children}</div>
              </main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
